language: python

matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
          after_success:
            - pip install coveralls
            - coveralls
        - python: 3.6
          env: TOXENV=docs
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8
          env: TOXENV=py38

install:
    - pip install tox tox-travis

script:
    - tox
