# -*- coding: utf-8 -*-
#
# Supvisors documentation build configuration file, created by
# sphinx-quickstart on Thu Jan  5 17:54:55 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

import os
import sys
from datetime import date

# -- General configuration ------------------------------------------------

# needs_sphinx = '1.0'

# Sphinx extension module names
extensions = ['sphinx.ext.autodoc', 'myst_parser']

# Add any paths that contain templates here, relative to this directory.
templates_path = []

# The suffix(es) of source filenames.
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# General information about the project.
year = date.today().year

project = u'Supvisors'
copyright = u'2016-{}, Julien Le Cléach'.format(year)
author = u'Julien Le Cléach'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The Supvisors version.
parent = os.path.dirname(os.path.dirname(__file__))
sys.path.append(os.path.abspath(parent))
version_txt = os.path.join(parent, 'supvisors/version.txt')
version = release = open(version_txt).read().split('=')[1].strip()

exclude_patterns = ['.build', 'Thumbs.db', '.DS_Store']

pygments_style = 'sphinx'

# -- Options for HTML output ----------------------------------------------

html_theme = 'sphinx_rtd_theme'

html_static_path = []
